In [1]:
#Fundamentos de Tensorflow
#Introducción a tensores
#Sacar info de tensores
#Manipulación de tensores
#Tensores y numpy
# @tf.function 
#Uso de GPU con tensorflow
#Ejercicios

In [2]:
#Introducción a tensores

In [3]:
#Importar tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [4]:
#Crear tensores con tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#Número de dimensiones de un tendor 
scalar.ndim

0

In [6]:
#Vectores
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#Dimensiones de un vector
vector.ndim

1

In [8]:
#Matrices
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
#Dimensiones de una matriz
matrix.ndim

2

In [10]:
#Crear otra matriz
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
#Tensores
tensor =tf.constant([[[1,2,3],
                   [4,5,6]],
                   [[7,8,9],
                   [10,11,12]],
                   [[13,14,15],
                   [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

In [14]:
#Hemos creado
#Scalar: número
#Vector: ńúmero con dirección
#Matriz: Un array 2D de números
#Tensor: Un array n-dimensional

In [15]:
#Creación de tensores con tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
#Cambiar elementos en el tensor variable 
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Usar .assign
changeable_tensor[0].assign(7)
changeable_tensor

In [17]:
#Probar en el unchangeable
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [18]:
#Creando tensores aleatorios
random_1 = tf.random.Generator.from_seed(42) #la seed
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(500)
random_2 = random_2.normal(shape =(3,2))

#Son iguales
random_1,random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.6467872 , -0.70762324],
        [-0.05593427, -0.52378434],
        [-0.02676746, -0.8452239 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [19]:
#Cambiar el orden de los elementos de un tensor
not_shuffled = tf.constant([
                            [10,7],
                            [3,4],
                            [2,5]])


In [20]:
#Deberes
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=6)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
#Otras maneras de hacer tensores
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [23]:
#Cambiar numpy arrays en tensores
import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(numpy_A,shape = (12,2))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(12, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [25]:
#Sacar información de tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
#Otros atributes
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensiones:",rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensiones: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


In [28]:
#Indexing tensores
#Dos primeros elementos de cada dimensión
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
#Conseguir el primer elemento de cada dimensión para cada índice excepto en la del final
rank_4_tensor[:,:,:1,:1]

<tf.Tensor: shape=(2, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]],


       [[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [30]:
#Crear un tensor 2D
rank_2_tensor = tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [31]:
#Conseguir un último elemento de nuestro tensor bidimensional
rank_2_tensor[:,-1].numpy()

array([7, 4], dtype=int32)

In [32]:
#Añadir una dimensión etra a un tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
#Alternativa a tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [35]:
#Manipulación de tensores
tensor = tf.constant([[10,7],[3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [36]:
#Tensor original sigue igual
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [37]:
#Multiplicación
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [38]:
#Resta
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [39]:
#También hay funciones de tensorflow para esto
tf.multiply(tensor,10) #más rápido que los operadores

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [40]:
#Multiplicación de matrices
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [41]:
#Operador multiplicador de matrices
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [42]:
tensor.shape

TensorShape([2, 2])

In [43]:
#Crear tensor (3,2)
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
#Crear otro tensor (3,2)
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [44]:
#Multiplicación
tf.matmul(X,Y)

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [45]:
#Cambiar la shape de Y 
tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [46]:
#Multiplicar ahora
X @ tf.reshape(Y, shape=((2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [47]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [48]:
#Cambiar las dimensiones de X en vez de Y
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [49]:
#Trasponer una matriz
tf.transpose(X),tf.reshape(X,shape=(2,3))
#Trasponer cambia el eje mientras que reshape solo reordena

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [50]:
 #Multiplicación de matrices con la traspuesta
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [51]:
#Producto escalar
tf.tensordot(tf.transpose(X),Y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [52]:
#Lo mismo pero con y traspuesta
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [53]:
#Lo mismo con Y reshaped
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [54]:
#Comprobar valores de Y, reformar Y y transponer
print("Y normal:")
print(Y,"\n")
print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)),"\n")
print("Y transposed:")
print(tf.transpose(Y),"\n")

Y normal:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



In [55]:
#Cambiando el tipo de datos
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [56]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [57]:
#Cambiar de float32 a float16
D = tf.cast(B,dtype=tf.float16)
D.dtype

tf.float16

In [58]:
#Cambiar de int32 a float32
E = tf.cast(C,dtype=tf.float32)
E.dtype

tf.float32

In [59]:
E_float16 = tf.cast(E,dtype=tf.float16)
E_float16.dtype

tf.float16

In [60]:
#Tensores agregados
#Agregar tensores es condensar sus valores
#Valor absoluto
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [61]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [62]:
#Más formas
E = tf.constant(np.random.randint(0,100,size=50))
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [63]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [64]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [65]:
tf.reduce_mean(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=51.2>

In [66]:
tf.math.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2561>

In [72]:
import tensorflow_probability as tfp
#tf.math.reduce_std(tf.cast(E,dtype=tf.float16))

In [74]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=827>

In [78]:
tf.math.reduce_std(tf.cast(E,dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=28.77>

In [81]:
#Posición de máximo y mínimo de un tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=([50]))
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [82]:
#Encuentra la posición del máximo
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [83]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [84]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [85]:
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [86]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [88]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [105]:
##Squeezing un tensor (eliminar dimensiones sueltas)
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [106]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [108]:
#Tensores de one-hot encoding
#Crear una lista de indices
some_list = [0,1,2,3]
#One hot encode
tf.one_hot(some_list,len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [110]:
#Valores de usuario para el one hot
tf.one_hot(some_list,10,on_value = "aka_b",off_value="bbeas")

<tf.Tensor: shape=(4, 10), dtype=string, numpy=
array([[b'aka_b', b'bbeas', b'bbeas', b'bbeas', b'bbeas', b'bbeas',
        b'bbeas', b'bbeas', b'bbeas', b'bbeas'],
       [b'bbeas', b'aka_b', b'bbeas', b'bbeas', b'bbeas', b'bbeas',
        b'bbeas', b'bbeas', b'bbeas', b'bbeas'],
       [b'bbeas', b'bbeas', b'aka_b', b'bbeas', b'bbeas', b'bbeas',
        b'bbeas', b'bbeas', b'bbeas', b'bbeas'],
       [b'bbeas', b'bbeas', b'bbeas', b'aka_b', b'bbeas', b'bbeas',
        b'bbeas', b'bbeas', b'bbeas', b'bbeas']], dtype=object)>

In [111]:
#Raíz cuadrada, cuadrados y logaritmos
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [112]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [115]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [119]:
tf.math.log(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [123]:
#Tensores y numpy 
#Crer tensor de array Numpy
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [124]:
#Convert tensor to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [126]:
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [128]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [131]:
#Tipos pretederminados para ambos
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

In [133]:
#Encontrar acceso a la GPU
tf.config.list_physical_devices("GPU")

[]

In [153]:
#Ejercicios
#1.
escalar = tf.constant(3)

vector = tf.constant([3,2])

matrix = tf.constant(tf.range([20]),shape = [4,5])

tensor = tf.constant(tf.eye(4),shape = [2,2,4])
#2
escalar.shape,vector.shape,matrix.shape,tensor.shape

(TensorShape([]),
 TensorShape([2]),
 TensorShape([4, 5]),
 TensorShape([2, 2, 4]))

In [157]:
#3
tensor_r_1 = tf.random.uniform(shape=[5,300])
tensor_r_2 = tf.random.uniform(shape=[5,300])
tensor_r_1,tensor_r_2

In [159]:
#4
tf.matmul(tensor_r_1,tf.transpose(tensor_r_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[79.870186, 78.38937 , 75.612785, 75.593025, 69.97791 ],
       [77.54845 , 73.29372 , 75.974174, 73.42592 , 70.43666 ],
       [79.4402  , 74.5689  , 76.65013 , 77.14311 , 72.57941 ],
       [83.247635, 78.040634, 77.689896, 74.93364 , 68.960014],
       [75.75107 , 75.892   , 71.79898 , 74.770935, 70.34851 ]],
      dtype=float32)>

In [163]:
#5
tf.tensordot(tensor_r_1,tensor_r_2,axes = [0,0])

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.4247695 , 1.1520683 , 1.7657367 , ..., 1.0479691 , 1.2181218 ,
        0.89086586],
       [0.39736137, 0.47433212, 0.5314674 , ..., 0.4343188 , 0.43589312,
        0.4407212 ],
       [1.891231  , 1.5539471 , 2.197358  , ..., 1.6780128 , 0.9632791 ,
        0.8943179 ],
       ...,
       [1.3911294 , 1.149694  , 1.5437838 , ..., 1.1839103 , 0.5128547 ,
        0.37942365],
       [1.3872374 , 1.0981553 , 1.6878893 , ..., 1.0683857 , 1.0181445 ,
        0.7981023 ],
       [0.7960243 , 0.70283204, 0.93279386, ..., 0.68523777, 0.47122037,
        0.37649754]], dtype=float32)>

In [164]:
#6
tensor_r_3 = tf.random.uniform([224,224,3],minval=0,maxval=1)

In [167]:
#7
tf.reduce_min(tensor_r_3,axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[1.09994411e-03, 7.80105591e-04, 2.68447399e-03],
       [1.07777119e-03, 1.92117691e-03, 1.17659569e-03],
       [4.49180603e-03, 2.62963772e-03, 1.58709288e-02],
       [4.94253635e-03, 1.02962255e-02, 1.05512142e-03],
       [1.74450874e-03, 2.51471996e-03, 4.08947468e-03],
       [6.15584850e-03, 6.20245934e-04, 4.65774536e-03],
       [5.74409962e-03, 7.48217106e-03, 4.52625751e-03],
       [2.52890587e-03, 4.82547283e-03, 3.66997719e-03],
       [7.67171383e-03, 5.51939011e-04, 7.99894333e-05],
       [1.72662735e-03, 1.83343887e-03, 2.77113914e-03],
       [3.16035748e-03, 2.40206718e-04, 1.31487846e-04],
       [6.81471825e-03, 2.73418427e-03, 6.95323944e-03],
       [1.68180466e-03, 1.30307674e-03, 4.77170944e-03],
       [1.68609619e-03, 1.31559372e-03, 1.08122826e-04],
       [1.68454647e-03, 4.33313847e-03, 1.55150890e-03],
       [2.02190876e-03, 3.74293327e-03, 7.11095333e-03],
       [2.96819210e-03, 2.17580795e-03

In [169]:
#8
tensor_r_4 = tf.random.uniform([1,224,224,3])
tf.squeeze(tensor_r_4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5749372 , 0.19900596, 0.7038239 ],
        [0.05541027, 0.5884645 , 0.5430788 ],
        [0.9185413 , 0.37144518, 0.84554374],
        ...,
        [0.6570301 , 0.7645861 , 0.48230588],
        [0.41497958, 0.4241538 , 0.5199896 ],
        [0.59315014, 0.23632371, 0.15606153]],

       [[0.34459436, 0.24155474, 0.8630327 ],
        [0.92559505, 0.41881108, 0.9492458 ],
        [0.21597803, 0.15805602, 0.9682605 ],
        ...,
        [0.45298254, 0.6097312 , 0.45232892],
        [0.04503286, 0.48371267, 0.7752477 ],
        [0.644374  , 0.65862846, 0.11632323]],

       [[0.18631506, 0.29340136, 0.3898226 ],
        [0.8457128 , 0.86194694, 0.05938876],
        [0.22856331, 0.74509835, 0.32373703],
        ...,
        [0.03299081, 0.8350847 , 0.77849007],
        [0.5707276 , 0.7097032 , 0.07139933],
        [0.6495327 , 0.17728817, 0.2139225 ]],

       ...,

       [[0.79031277, 0.3867849 , 0.21375918],
        [0.25

In [175]:
#9
tensor_10 = tf.random.uniform(shape =[10],minval=0,maxval= 15,dtype=tf.int32)
tf.argmax(tensor_10)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [180]:
tf.one_hot(tensor_10,15)

<tf.Tensor: shape=(10, 15), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>